
db.driverClassName=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://localhost:3306/dbsaas?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
db.username=dbsaas
db.password=123456

################################
# HikariCP
################################

hikari.maximum-pool-size=10
hikari.minimum-idle=2
hikari.connection-timeout=30000
hikari.idle-timeout=600000
hikari.max-lifetime=1800000

upload.path=file:///C:/dev/workspace/dbsaas/upload/
tmp.path=file:///C:/dev/workspace/dbsaas/tmp/

log.level=DEBUG

